/* eslint-disable */
/**
 * Generated by convex dev. Will be overwritten on next run.
 * This stub file allows TypeScript to compile before `npx convex dev` is run.
 */
import type { AnyApi } from 'convex/server'

declare const api: AnyApi
export { api }
