/* eslint-disable */
/**
 * Generated by convex dev. Will be overwritten on next run.
 * This stub file allows TypeScript to compile before `npx convex dev` is run.
 */

// Stub ID type that matches Convex's generated Id type
export type Id<TableName extends string> = string & { __tableName: TableName }

export type DataModel = Record<string, any>
